### ISSUE TITLE
Login screen signup text

### ISSUE THREAD

**Issue by emil01** [netbeast/dashboard#128]
On the login page the text should read:

**Don't have an account? Sign Up**

And on the Sign up page the text should read:

**Already have an account? Login**

FYI, this is from an npm install

![login bug](https://cloud.githubusercontent.com/assets/315038/15178295/cf4b0de4-1785-11e6-85d9-bccef3722412.png)
![signup bug](https://cloud.githubusercontent.com/assets/315038/15178550/40f1ce0a-1787-11e6-8855-9d686f4ac979.PNG)

---------------------------------------------------------------------------------------------------------------------------------------

On docker the text says **Sing Up** instead of **Sign up** :smile: 

![docker page](https://cloud.githubusercontent.com/assets/315038/15179197/612ccad6-178b-11e6-9a25-66bd3b541eff.PNG)

**Comment by jsdario** [comment]
Great thanks! 
It should be fixed soon with our last PR https://github.com/netbeast/dashboard/pull/122

Log in & Sign up however are on `alpha` and we are going to hide it in next releases again.

**Comment by jsdario** [comment]
Solved, thanks a lot @emil01. You can check it live in https://dashboard.netbeast.co.

By the way, login works already, we are now working on private access to your remote device Dashboard.
