### ISSUE TITLE
When I click on an Application or Plugin nothing happens

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/dashboard#147]
##### 1. Describe your issue ( Expected and actual behaviour )

When I install one application or plugin and then I click on them to run it nothing happens I think can be a problem with the UI
  
  
##### 2. Steps to reproduce the problem

  Install any application or plugin and  click on it on 

##### 3. Please left us some versioning details like..

    * Where is the dashboard running (OS): Linux
    * Dashboard version: Latest
    * npm & node version: 5.8.0
  
  
Thanks, I hope we can figure it out as fast as posible :)

**Comment by luisfpinto** [comment]
I'm using firefox as browser.

**Comment by pablopi** [comment]
Safari is also buggy. It doesn't show nothing. only a grey background..

**Comment by luisfpinto** [comment]
Solved :+1:
