### ISSUE TITLE
ENOENT: no such file or directory, scandir './_apps' at error (native)

### ISSUE THREAD

**Issue by jsdario** [netbeast/dashboard#148]
##### 1. Describe your issue ( Expected and actual behaviour )
Appears `ENOENT: no such file or directory, scandir './_apps' at error (native)` after first run after npm installation.  
  
##### 2. Steps to reproduce the problem
You can find the discussion on the forum, here: http://forum.netbeast.co/t/netbeast-start-not-working/58/18

##### 3. Please left us some versioning details like..

    * Raspbian
    * Last
    * Node v6+

**Comment by luisfpinto** [comment]
Solved here https://github.com/netbeast/dashboard/commit/7df586ccaca6b1d2ac4ad2c5b13bb331936ea0c6
