### ISSUE TITLE
Beast new app and beast new plugin doesn't work

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/dashboard#149]
##### 1. Describe your issue ( Expected and actual behaviour )

  When I try to do beast new app or beast new plugin after installing the npm module it doesn't work due to submodules are not cloned properly .

```
 return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/netbeast-cli/lib/../bin/bundles/base-app'
```
  
  
##### 2. Steps to reproduce the problem

  Install npm module. 
Try to beast new app/plugin

##### 3. Please left us some versioning details like..

    * Where is the dashboard running (OS): Linux
    * Dashboard version: Last
    * npm & node version: Last
  
  
Thanks, I hope we can figure it out as fast as posible :)

**Comment by pablopi** [comment]
solved
