### ISSUE TITLE
Some repos are not being discovered

### ISSUE THREAD

**Issue by Bigomby** [netbeast/dashboard#157]
##### 1. Describe your issue ( Expected and actual behaviour )

The query used to find Netbeast plugins on GitHub looks only for JavaScript repos, but some repos has more HTML than JS so is considered by GitHub an HTML repo.

This situation makes my repo not being included in the query result so it won't be displayed on dashboard discover section.
    
##### 2. Steps to reproduce the problem

Create a repo for an app or a plugin where the main language is not JavaScript.

Example repo: https://github.com/Bigomby/netbeast-yeelight

**Comment by jsdario** [comment]
It has a quickfix – @luisfpinto gonna make a PR soon. Thanks for reporting :D

**Comment by luisfpinto** [comment]
I think it is fixed on the new commit https://github.com/netbeast/dashboard/commit/c44c729f0ec7387fb5b11c5bf1b20b4bfd4e67cb

Check it out and if it works, close the issue 😄 

Thank you for reporting the issue! 🚀

**Comment by Bigomby** [comment]
Nice, it works now.
