### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by captinhood** [netbeast/dashboard#163]
##### 1. Describe your issue ( Expected and actual behaviour )

  ...
  
  
##### 2. Steps to reproduce the problem

  ...

##### 3. Please left us some versioning details like..

    * Where is the dashboard running (OS): 
    * Dashboard version: 
    * npm & node version: 
  
  
Thanks, I hope we can figure it out as fast as posible :)

**Comment by jsdario** [comment]
Sorry, what is the actual problem?
