### ISSUE TITLE
update dashboard action outdated

### ISSUE THREAD

**Issue by TheHenning** [netbeast/dashboard#4]
Update Dashboard in the settings panel of the netbeast dashboard is not working at the moment.

**Comment by jsdario** [comment]
I am taking a look. It seems that it effectively updates the dashboard but it does not prompt any toast (in the latest version) 

![screen shot 2015-12-04 at 18 01 18](https://cloud.githubusercontent.com/assets/5166506/11595696/0caa6b32-9ab1-11e5-82d3-859a254af40b.png)

It will take several days till I be back on this, you got the update script available here:
https://github.com/netbeast/dashboard/blob/master/src/routes/misc.js

If you feel confident you can try to fix it and make a pull request ;)

**Comment by jsdario** [comment]
Closing until future review from the [community](https://forum.netbeast.co)
