### ISSUE TITLE
Error using superagent with form-data

### ISSUE THREAD

**Issue by cayrodmed1** [netbeast/dashboard#40]
When trying to use `superagent` instead of `request` in tests, I'm getting an error with 2 tests. This tests both use form-data. In `request` it is like:
```
var request = require('request')
var req = request.post(URL + '/apps', function (err, resp, body) {
     // Test code
    })
var form = req.form()
var app = path.join(__dirname, '../app.tar.gz')
form.append('file', fs.createReadStream(app))
```
I've found out that `attach` is the equivalent for `append` in `superagent`, so with `superagent` it would be:
```
var agent = require('superagent')
var app = path.join(__dirname, '../app.tar.gz')
agent.post(URL + '/apps')
    .attach('file', fs.createReadStream(app))
    .end(function (err, resp, body) {
     // Test code
    })
```
I execute this code and dashboard throws the following error: 

> Error: App must be a .tar.gz file.

And this throws the 422 error (Unprocessable Entity) in tests.

It seems like it doesn't take the route to the app properly, but I don't know why it happens.

Any idea? Am I doing something wrong?

**Comment by pablopi** [comment]
It doesn't look a problem with the app route.
I don't know exactly how .attach() works, but maybe you should look into /middleware/installer.js file. There is were the request is processed.
 Analyze the request trying to figure out if it is something missing.
if you still feeling lost I can take a look later :)

**Comment by cayrodmed1** [comment]
I'm sure I'm using .attach() properly (like `superagent` documentation https://visionmedia.github.io/superagent/#multipart-requests).
I had a look at /middleware/installer.js but I can't get what is wrong with my code.

**Comment by pablopi** [comment]
I saw that the mimetype of the file on both scenarios are different. This is causing the rejection.

REQUEST
````
{ fieldname: 'file',
  originalname: 'app.tar.gz',
  encoding: '7bit',
  mimetype: 'application/octet-stream' }
````
SUPERAGENT
````
{ fieldname: 'file',
  originalname: 'app.tar.gz',
  encoding: '7bit',
  mimetype: 'false' }
````

**Comment by cayrodmed1** [comment]
I tried adding this line to the code: `.set('Content-Type', 'application/octet-stream')` but still getting same error.

**Comment by luisfpinto** [comment]
You have to put .set('Content-Type', 'application/octet-stream') after the .post and before attach. Don't now if you have done it in that way

**Comment by cayrodmed1** [comment]
Yes, I'm doing it like this. This is the full code:
```
var agent = require('superagent')
var app = path.join(__dirname, '../app.tar.gz')
agent.post(URL + '/apps')
    .set('Content-Type', 'application/octet-stream')
    .attach('file', fs.createReadStream(app))
    .end(function (err, resp, body) {
     // Test code
    })
```

**Comment by jsdario** [comment]
Is this still happening?

`application/octet-stream` is being set on all post body, but maybe it is required to be set as file property. There is a slight difference between both.

Try using **app.tar.gz** path instead `fs.createReadStream`, since a stream is not a proper file and, thus, has not mimetype as in https://visionmedia.github.io/superagent/#multipart-requests

```
var agent = require('superagent')
var app = path.join(__dirname, '../app.tar.gz')
agent.post(URL + '/apps')
    .attach('file', app)
    .end(function (err, resp) {
     // Test code
    })
```

**Comment by cayrodmed1** [comment]
I've tried using app.tar.gz as path but it doesn't fix the issue.

**Comment by jsdario** [comment]
This is apparently a problem with `superagent` itself https://github.com/visionmedia/superagent/issues/746. However you did great. I'll patch it the best I can. Thanks @cayrodmed1.
