### ISSUE TITLE
Impossible to launch application error - caused by node module

### ISSUE THREAD

**Issue by TheHenning** [netbeast/dashboard#5]
I installed my app which is perfectly running localy, on the raspberry pi through the dashboard. But it is somehow impossible to launch...

![01111](https://cloud.githubusercontent.com/assets/16143239/11643910/6defc322-9d47-11e5-9dd2-21d9d71a1fb1.jpg)

If you wonder why this error occures, try to 'test' every node module you are using on its own in a clean new app!

In my case, it seems the npm module 'lwip' is the bad guy... when I just require this module in myapp I get the error. Netbeast OS or Raspberry Pi seem to fail requesting this module. Could it be because 'lwip' is custom compiled when you type 'npm install lwip'?

**Comment by TheHenning** [comment]
I went further and installed lwip manually and globaly on the raspberry pi and it runs without problems on its own. I deleted the local lwip module of my app on the raspberry pi. Afterwards I linked the global package to my previously created app in /etc/netbeast/dashboard/.sandbox/myfailapp using 'npm link lwip'. 

Running the app from terminal using sudo now shows the following error :

pi@netbeast /etc/netbeast/dashboard/.sandbox/myfailapp $ sudo node server.js
module.js:83
    throw e;
    ^

SyntaxError: Error parsing /etc/netbeast/dashboard/.sandbox/myfailapp/node_modules/express/node_modules/send/node_modules/destroy/package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:79:52)
    at tryPackage (module.js:89:13)
    at Function.Module._findPath (module.js:152:20)
    at Function.Module._resolveFilename (module.js:335:25)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/etc/netbeast/dashboard/.sandbox/myfailapp/node_modules/express/node_modules/send/index.js:14:15)
    at Module._compile (module.js:435:26)
pi@netbeast /etc/netbeast/dashboard/.sandbox/myfailapp $ 

Is anybody aware of such an issue with other node modules or even better has a quickfix? :)

**Comment by jsdario** [comment]
Seems to be a problem with such package dependency. However it seems to be
a express depedency and should work fine.

Try not to npm link if various packages share same dependency and different
versions.

Anyhow this is just a guess I will try to reproduce the failure if you keep
finding the same problem.

**Comment by TheHenning** [comment]
I tried it again on the netbeast with the original local lwip module in the node modules folder:

pi@netbeast /etc/netbeast/dashboard/.sandbox/nodeapp $ sudo node server.js
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /etc/netbeast/dashboard/.sandbox/nodeapp/node_modules/lwip/build/Release/lwip_image.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /etc/netbeast/dashboard/.sandbox/nodeapp/node_modules/lwip/lib/Image.js:3:22
    at Object.<anonymous> (/etc/netbeast/dashboard/.sandbox/nodeapp/node_modules/lwip/lib/Image.js:16:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
pi@netbeast /etc/netbeast/dashboard/.sandbox/nodeapp $ 

Any suggestions? 

[app.tar.gz](https://github.com/netbeast/dashboard/files/55152/app.tar.gz)

**Comment by pablopi** [comment]
I have installed the app through the dashboard, and then go into the app folder and run:
sudo npm rm lwip
sudo npm install lwip
and it works. Did you  try this??

**Comment by TheHenning** [comment]
**Solved the Problem**

The Problem was that node modules compiled on the mac were not working on the raspberry pi.

If you encounter the "Impossible to launch application" error when you try to start your app on the dashboard, try the following:

To find out if this is your error-
1. Create a new clean app with 'netbeast new myapp'
2. Identify every node module which was compiled when you did 'sudo npm install modulname --save'
3. Intall just this module in your app and require it in the server.js
4.Upload the app to the netbeast dashboard on the raspberry pi
5. run the app in the /etc/netbeast/dashboard/.sandbox/yourapp folder on the terminal
you should get something like this - Error: /etc/netbeast/dashboard/.sandbox/...: invalid ELF header 

To solve this errror-
1. Connect to your raspberry pi using the terminal
2. Delete the identified node modules in /etc/netbeast/dashboard/.sandbox/YOURAPP/node_modules/
3. Install using 'sudo npm install MODULNAME --save' the previously deleted node modules
4. Now the node modules are directly compiled on the raspberry pi and should work like charm
5. Have fun!
