### ISSUE TITLE
spawn is not working

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/dashboard#51]
I think spawn is not working. I have tried to clone the repo, install packages and the dashboard doesn't detect any devices, even the beast scan process can't reach the dashboard. Can you try and see if I am right?

**Comment by jsdario** [comment]
Hopefully this works now, will rebase in electron branch in a moment:

https://github.com/netbeast/dashboard/pull/52

**Comment by luisfpinto** [comment]
It works! :fireworks:
