### ISSUE TITLE
Error message when I install and application

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/dashboard#6]
![screen shot 2015-12-14 at 14 01 23](https://cloud.githubusercontent.com/assets/9916242/11781675/b0a5887c-a26b-11e5-9bcc-c3b65b34edc2.png)

When I install an application I don't know why there is a message under the app logo that says :
"data-dz-errormessage"

@netbeast/engineering

**Comment by jsdario** [comment]
Last release completely changes the aspect of the dashboard.
