### ISSUE TITLE
Warning messages are not red

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/dashboard#64]
I don't know, when a error appears on the dashboard, It doesn't look red

**Comment by jsdario** [comment]
Fixed https://github.com/netbeast/dashboard/commit/9e997514520297d56e9e8c0013e2829d37049f2d.

<img width="335" alt="screen shot 2016-03-20 at 14 27 10" src="https://cloud.githubusercontent.com/assets/5166506/13904838/a3bd4738-eead-11e5-9a62-aa3ce07e0331.png">
