### ISSUE TITLE
Add engine(s) to package.json

### ISSUE THREAD

**Issue by iblancasa** [netbeast/dashboard#66]
It is important. For example, in Ubuntu 14.04 PPA installs version 0.10.x... and the latest stable version is (I think) v5.9.0. The problem is: some dependences use thinks like "Promises", not implemented in old versions.
If you say with what version of Node are you developing, will be easier for developers to edit/revise/etc code :+1:

**Comment by jsdario** [comment]
:+1: https://github.com/netbeast/dashboard/pull/69
