### ISSUE TITLE
Troubles when I try to install beast-red app

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/dashboard#67]
I have some troubles when I try to install [beast-red](https://github.com/netbeast/beast-red). It looks like app installation never ends and when I try to run the app some errors come up. Could you please check if this error is due to the dashboard or in the opposite this id due to the app. 

Thanks!

**Comment by jsdario** [comment]
Installation takes long. Be patient (15 secs in my case) because the repo has no `node_modules` folder. This is the right way, but `npm install` will take ages. You can try it yourself.

The installation was just right, in any case.

Plus, once installed, **there is a problem with the app:**
<img width="564" alt="screen shot 2016-03-20 at 13 17 07" src="https://cloud.githubusercontent.com/assets/5166506/13904363/6d154190-ee9e-11e5-9370-79e365fa19e5.png">

**Comment by jsdario** [comment]
Check last version of the dashboard https://github.com/netbeast/dashboard/pull/68 `master` branch. Now some progress feedback when installing.

<img width="337" alt="screen shot 2016-03-20 at 13 49 19" src="https://cloud.githubusercontent.com/assets/5166506/13904517/ca3d129e-eea3-11e5-9b1d-60001ce43a00.png">

**Comment by luisfpinto** [comment]
Nice! :+1:

**Comment by cayrodmed1** [comment]
I don't get why are this errors throwing while trying to use the app. Any idea?

**Comment by jsdario** [comment]
Looks pretty cryptic. I'll take a look tomorrow and try to help

**Comment by jsdario** [comment]
Any progress? want to close this issue!

**Comment by luisfpinto** [comment]
On my computer When I try to launch the app I get:

```
Exception in routes stack:
Error: Impossible to launch the application
    at keepTrying (/Users/luisf/Netbeast/dashboard/src/models/activity.js:65:38)
    at Timer.listOnTimeout (timers.js:92:15)
```

I think that should be due to the time that dashboard waits until It tries to launch the app. 

Regarding the original problem, I don't know if It has been solved

**Comment by cayrodmed1** [comment]
I was trying to fix this problem last week but I couldn't find a solution. I added a `index.html` file and used `browserify` to create a `bundle.js` file for the `red.js `file (main file of the app).
I still get the same error you're receiving with the timer, but I don't really know how to fix this.
