### ISSUE TITLE
Notifications don't work on firefox

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/dashboard#82]
When I try to see notification history I get the following error:

```
Error: Objects are not valid as a React child (found: object with keys {type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Toast`.
```

After that the dashboard crashes

**Comment by jsdario** [comment]
Fixed in https://github.com/netbeast/dashboard/pull/84 https://github.com/netbeast/dashboard/pull/83

![screen shot 2016-04-20 at 17 46 27](https://cloud.githubusercontent.com/assets/5166506/14681043/d656babe-071f-11e6-8949-6916d6cfb889.png)

:+1:
